name: deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Sync frontend to S3
        run: |
          aws s3 sync frontend/out s3://${{ secrets.FRONTEND_BUCKET }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} --paths "/*"

      - name: Package backend
        working-directory: backend
        run: |
          npm ci
          zip -r backend.zip . -x "node_modules/*"
          aws lambda update-function-code --function-name telehealth-voice-api --zip-file fileb://backend.zip
